name: bavard
description: A Laravel Eloquent-like ORM for PowerSync, sqlite or PostgreSQL.

version: 0.0.1

environment:
  sdk: ^3.10.1

dependencies:
  uuid: ^4.5.2

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  source_gen: ^4.1.1
  analyzer: ^9.0.0