name: bavard
description: An Laravel Eloquent-inspired ORM for Flutter. Supports SQLite, PostgreSQL and PowerSync with fluent queries, relationships, soft deletes, timestamps, casts and more.
version: 0.0.10
homepage: https://github.com/ILDaviz/bavard
repository: https://github.com/ILDaviz/bavard
topics:
  - orm
  - flutter
  - dart
  - powersync
  - sqlite

environment:
  sdk: ^3.10.1

dependencies:
  uuid: ^4.5.2
  build: ^4.0.0
  build_runner: ^2.10.4
  source_gen: ^4.1.1
  analyzer: ^9.0.0

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0
