name: bavard
description: An Eloquent-inspired ORM for Flutter. Supports SQLite, PostgreSQL and PowerSync with fluent queries, relationships, soft deletes, timestamps, casts and more.
version: 0.0.19
homepage: https://ildaviz.github.io/bavard/
repository: https://github.com/ILDaviz/bavard
topics:
  - orm
  - flutter
  - dart
  - powersync
  - sqlite

environment:
  sdk: ^3.10.1

dependencies:
  uuid: ^4.5.2
  build: ^4.0.3
  build_runner: ^2.10.0
  source_gen: ^4.1.1
  analyzer: ">=7.0.0 <10.0.0"

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
