name: bavard
description: A Laravel Eloquent-like ORM for PowerSync, sqlite or PostgreSQL.

version: 0.0.4

environment:
  sdk: ^3.10.1

dependencies:
  uuid: ^4.5.2

dev_dependencies:
  test: ^1.24.0
  lints: ^2.0.0
  build_runner: ^2.10.4
  source_gen: ^4.1.1
  analyzer: ^9.0.0