name: bavard
description: An Laravel Eloquent-inspired ORM for Flutter. Supports SQLite, PostgreSQL and PowerSync with fluent queries, relationships, soft deletes, timestamps, casts and more.
version: 0.0.12
homepage: https://github.com/ILDaviz/bavard
repository: https://github.com/ILDaviz/bavard
topics:
  - orm
  - flutter
  - dart
  - powersync
  - sqlite

environment:
  sdk: ^3.10.1

dependencies:
  uuid: ^4.5.2
  build_runner: ^2.4.0
  analyzer: ">=6.0.0 <10.0.0"
K  source_gen: ^1.5.0
  build: ^2.4.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
