name: bavard_sqlite_test
description: A test environment for Bavard with SQLite in Docker.
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bavard:
    path: /app/bavard
  sqlite3: ^2.0.0
