name: bavard_migration
description: Migration system for Bavard ORM.
version: 0.0.2
resolution: workspace
publish_to: 'none'

environment:
  sdk: ^3.10.1

dependencies:
  bavard: ^0.0.1
  bavard_cli: ^0.0.1
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
