name: bavard_cli
description: Command line interface for Bavard ORM.
version: 0.0.2
resolution: workspace

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
