name: bavard_example_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bavard:
    path: ../bavard
  bavard_migration:
    path: ../bavard_migration
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6

dependency_overrides:
  bavard:
    path: ../bavard
  bavard_migration:
    path: ../bavard_migration
  bavard_cli:
    path: ../bavard_cli

flutter:
  uses-material-design: true
